Add support for `cal` and `ncal` commands
dodona-edu/docker-images pull request #118
Opened 2020-09-24 14:44 UTC by pverscha

These commands are required for some exercises in the "Computergebruik" course.

2020-09-24 15:22 UTC, charvp requested changes

2020-09-24 15:22 UTC, charvp commented on dodona-bash.dockerfile
> +        bsdmainutils=12.1.7 \
```suggestion
        bsdmainutils=11.1.2+b1 \
```
This is the version for debian buster (tested locally).

2020-09-25 07:46 UTC, pverscha commented on dodona-bash.dockerfile
> +        bsdmainutils=12.1.7 \
Yes, this should be the one :) Thanks!

2020-09-25 07:48 UTC, pverscha commented
Thanks @charvp! This should indeed be the correct version, I did not look thoroughly enough yesterday ;)

2020-09-25 07:49 UTC, charvp approved these changes

2020-09-25 07:49 UTC, merged