Add Dockerfile for Compilers course
dodona-edu/docker-images pull request #308
Opened 2024-01-04 15:33 UTC by thomasfaingnaert

For the Compilers course at UGent, we'd like to use Dodona starting from this academic year.
This PR adds a Dockerfile for the Compilers labs, containing LLVM 13.0.0 and the LLVM testing utils.

NOTE: Rather than building LLVM in the Dockerfile, I download a pre-built version from https://github.com/thomasfaingnaert/llvm-builds, but I can move the compilation here, if needed.

// cc: @wkverstr

2024-01-05 09:12 UTC, chvp commented
Which judge are you planning on using this with? Is it a possibility to add these dependencies to the corresponding dockerfile for that judge?

2024-01-09 15:04 UTC, thomasfaingnaert commented
> Which judge are you planning on using this with? Is it a possibility to add these dependencies to the corresponding dockerfile for that judge?

The judge is hosted at https://github.com/wkverstr/judge-compilers at the moment.
Do you mean the `psutil` and `lit` Python dependencies? Sure, we can move those to the judge's `requirements.txt`.

2024-01-10 10:06 UTC, chvp requested changes
Could you also add this dockerfile to the CI workflows?

2024-01-11 14:28 UTC, chvp approved these changes

2024-01-11 14:28 UTC, merged